port: /dev/ttyDXL_puppet_right

groups:
  arm:
    operating_mode: position
    profile_type: time
    profile_velocity: 0
    profile_acceleration: 0
    torque_enable: true

singles:
  gripper:
    operating_mode: pwm
    profile_type: time
    profile_velocity: 0
    profile_acceleration: 0
    torque_enable: true
